v

# Startup
u 0x8057

# OperMode
display 0x0770
# OperMode_Task
display 0x0772
# ScreenRoutineTask
display 0x073c
# ColumnSets
#display 0x071e

# InitializeGame (0)
nmi
f

# ScreenRoutines (1) - InitScreen (0)
nmi
f

# ScreenRoutines (1) - SetupIntermediate (1)
nmi
f

# ScreenRoutines (1) - WriteTopStatusLine (2)
nmi
f

# ScreenRoutines (1) - WriteBottomStatusLine (3)
nmi
f

# ScreenRoutines (1) - DisplayTimeUp (4)
nmi
f

# ScreenRoutines (1) - DisplayIntermediate (6)
nmi
f

# ScreenRoutines (1) - AreaParserTaskControl (8)
# Do this 12 times

nmi
f
nmi
f
nmi
f
nmi
f
nmi
f
nmi
f
nmi
f
nmi
f
nmi
f
nmi
f
nmi
f
nmi
f

# ScreenRoutines (1) - GetAreaPalette (9)
nmi
f

# ScreenRoutines (1) - GetBackgroundColor (A)
nmi
f

# ScreenRoutines (1) - GetAlternatePalette1 (B)
nmi
f

# ScreenRoutines (1) - DrawTitleScreen (C)
nmi
f

# ScreenRoutines (1) - ClearBuffersDrawIcon (D)
nmi
f

# ScreenRoutines (1) - WriteTopScore (E)
nmi
f

# PrimaryGameSetup (2)
nmi
f

render
q

v
